GET https://missionary-ews-int.churchofjesuschrist.org/ws/missionary-ews/v1.5/rest/missions/proselyting_areas?ecclUnitNumber=176028
Accept: application/json
Authorization: Basic {{username}} {{password}}

<> 2020-05-05T115159.200.json

###
GET https://{{host}}:{{port}}/v2/accounts/2477661/entities/538-3617?api_key=897b3387e6f05a6fe3a9dfd05666c8fa&v=20200420
Accept: application/json

<> 2020-05-05T115548.200.json


###
GET https://{{host}}:{{port}}/v2/accounts/2477661/entities/538-3617?api_key=897b3387e6f05a6fe3a9dfd05666c8fa&v=20200420
Accept: application/json

<> 2020-05-05T115556.200.json


###
